"""Integration self-check: a config generated by config_gen must boot the REAL bot engine.

Catches drift between config_gen's template specs and what bot/engine + bot/strategies expect.
No Postgres, no network, no live keys: builds the Engine object (constructs strategies, risk,
client) from a generated per-user config in DRY_RUN. Does not run the poll loop.

Run:  python strattice/worker/selfcheck.py
"""
from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))          # so `import bot.*` resolves
sys.path.insert(0, str(Path(__file__).resolve().parent))  # flat worker imports

import config_gen  # noqa: E402


def main() -> None:
    tmp = Path(tempfile.mkdtemp(prefix="coindcx_sc_"))
    os.environ["BOT_DB_PATH"] = str(tmp / "bot.db")     # isolate from the real data/bot.db
    os.environ["CONFIG_PATH"] = str(tmp / "config.yaml")
    os.environ.setdefault("DRY_RUN", "true")

    from bot import audit, config       # imported AFTER env is set
    from bot.engine import Engine

    req = [
        {"template": "tsmom", "market": "I-ETH_INR", "enabled": True},
        {"template": "supertrend", "market": "I-BTC_INR", "enabled": True},
        {"template": "squeeze_breakout", "market": "I-DOGE_INR", "enabled": True},
        {"template": "rsi", "market": "I-ETH_INR", "enabled": True},  # retired legacy row
    ]

    # pricing is off: every tier is fully unlocked, so all 4 rows stay active.
    for tier, expect_active in (("free", 4), ("plus", 4), ("max", 4)):
        cfg = config_gen.build_config(tier, req, kill_switch_file="data/users/test/KILL")
        config_gen.write_config(Path(os.environ["CONFIG_PATH"]), cfg)
        loaded = config.load()                 # honors CONFIG_PATH (the 2-line bot change)
        assert loaded == cfg, f"{tier}: config.load() != generated config"
        audit.init()                           # creates tables in the temp DB
        eng = Engine(loaded)                   # builds strategies + risk + client (no network)
        assert eng.risk.max_trades_per_day == config_gen.entitlements.resolve(tier).trades_per_day
        # engine's active set = enabled strategies (+ any disabled-but-open; none here, fresh DB)
        n_enabled = sum(s.get("enabled", True) for s in loaded["strategies"])
        assert len(eng.strategies) == n_enabled, (tier, len(eng.strategies), n_enabled)
        assert n_enabled == expect_active, (tier, "active", n_enabled, expect_active)
        print(f"  {tier}: trades/day={eng.risk.max_trades_per_day} active_strategies={n_enabled} OK")

    print("selfcheck (config_gen -> real engine) OK")


if __name__ == "__main__":
    main()
